<?php


namespace portalium\site\components;

use portalium\user\models\User;
use Yii;
use yii\helpers\Json;
use yii\base\BaseObject;
use diginova\gebe\Module;
use diginova\task\models\Task;
use diginova\task\models\TaskData;
use portalium\site\models\Setting;
use diginova\task\models\TaskGroup;
use portalium\user\models\UserGroup;
use diginova\task\models\TaskAssignee;
use diginova\task\models\TaskTypeForm;
use diginova\task\models\TaskTypeHtml;

class TaskAutomation extends BaseObject
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function onUserCreate($event)
    {
        ['id' => $id] = $event->payload;
        $auth = Yii::$app->authManager;
        $settings = yii\helpers\ArrayHelper::map(Setting::find()->asArray()->all(),'name','value');
        $role = $settings['admin::user_role'];
        $role = (isset($role) && $role != '' && $role != '0') ? $auth->getRole($role) : $auth->getRole('user');
        
        if ($auth->getAssignment('user', $id)) {
            var_dump('user already assigned');
            return;
        }
        $auth->assign($role, $id);

    }
}