<?php

namespace portalium\site\components;

use Yii;
use yii\base\BaseObject;

class TriggerActions extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function onUserCreateBefore($event)
    {
        ['id' => $id_user] = $event->payload;
        
        $defaultUserRole = Yii::$app->setting->getValue('site::user_role');

        if ($defaultUserRole) {
            $auth = Yii::$app->authManager;
            $role = $auth->getRole($defaultUserRole);
            $auth->assign($role, $id_user);
        }
    }
}